//Tipos de Datos
console.log(24)
console.log(typeof 24)
console.log(2.3)
console.log(typeof 2.3)
console.log(true)
console.log(typeof true)
console.log("Hola Mundo")
console.log(typeof "Hola Mundo")
console.log(typeof null)
console.log(typeof undefined)
console.log([1, 2, 3])
console.log(typeof [1, 2, 3])
console.log({ nombre: "Diego"})
console.log(typeof { nombre: "Diego"})